apiVersion: v1
kind: Service
metadata:
  name: restaurant-order-ci-api
spec:
  type: ClusterIP
  selector:
    app: restaurant-order-api
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
