version: '3.4'

networks:
  restaurant-booking-service:

services:
  identity-service-api:
    container_name: identity-service-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Data Source=restaurant-booking-service-mssql-db;Initial Catalog=RestaurantIdentityService;User ID=sa;Password=1q2w3e4r5t6yY7u8i9o;TrustServerCertificate=True
      - JWTSecret=7SDA9d34as8oiog5ASVNNde8pioFDSG3gJ6sLNU1YE5RD
      - JWTExpirationTime=00:02:59
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/var/sertificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
    image: ${DOCKER_REGISTRY-}identity-service-api
    ports:
      - 8070:80
      - 8080:443
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mssql-db
    networks:
      - restaurant-booking-service
    volumes:
      - ./sertificate.pfx:/var/sertificate.pfx
  catalog-service-api:
    container_name: catalog-service-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Data Source=restaurant-booking-service-mssql-db;Initial Catalog=RestaurantCatalogService;User ID=sa;Password=1q2w3e4r5t6yY7u8i9o;TrustServerCertificate=True
      - JWTSecret=7SDA9d34as8oiog5ASVNNde8pioFDSG3gJ6sLNU1YE5RD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/var/sertificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
    image: ${DOCKER_REGISTRY-}catalog-service-api
    ports:
      - 8071:80
      - 8081:443
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mssql-db
    networks:
      - restaurant-booking-service
    volumes:
      - ./sertificate.pfx:/var/sertificate.pfx
  booking-service-api:
    container_name: booking-service-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Host=restaurant-booking-service-postgre-sql;Port=5432;Database=RestaurantBookingServiceDb;Username=altakomauser;Password=mypwd
      - JWTSecret=7SDA9d34as8oiog5ASVNNde8pioFDSG3gJ6sLNU1YE5RD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/var/sertificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
    image: ${DOCKER_REGISTRY-}booking-service-api
    ports:
      - 8072:80
      - 8082:443
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgre-sql
    networks:
      - restaurant-booking-service
    volumes:
      - ./sertificate.pfx:/var/sertificate.pfx
  mssql-db:
    container_name: restaurant-booking-service-mssql-db
    environment:
      -  ACCEPT_EULA=Y
      -  MSSQL_SA_PASSWORD=1q2w3e4r5t6yY7u8i9o
    ports:
      - 14433:1433
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - mssql-data:/var/lib/mssql-data
    networks:
      - restaurant-booking-service
  postgre-sql:
    container_name: restaurant-booking-service-postgre-sql
    environment:
      - POSTGRES_DB=RestaurantBookingServiceDb
      - POSTGRES_USER=altakomauser
      - POSTGRES_PASSWORD=mypwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 8888:5432
    image: postgres:16.0
    volumes:
      - postgre-data:/var/lib/postgresql/data
    networks:
      - restaurant-booking-service
volumes:
  mssql-data:
  postgre-data: