version: '3.4'

networks:
  identity-service:

services:
  identity-service-api:
    container_name: identity-service-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Data Source=sql-db;Initial Catalog=RestaurantIdentityService;User ID=sa;Password=1q2w3e4r5t6yY7u8i9o;TrustServerCertificate=True
      - JWTSecret=7SDA9d34as8oiog5ASVNNde8pioFDSG3gJ6sLNU1YE5RD
      - JWTExpirationTime=00:02:59
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/var/sertificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
    image: ${DOCKER_REGISTRY-}identity-service-api
    ports:
      - 8070:80
      - 8080:443
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - sql-db
    networks:
      - identity-service
    volumes:
      - ./sertificate.pfx:/var/sertificate.pfx
  sql-db:
    container_name: identity-service-db
    environment:
      -  ACCEPT_EULA=Y
      -  MSSQL_SA_PASSWORD=1q2w3e4r5t6yY7u8i9o
    ports:
      - 14433:1433
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sql-data:/var/lib/sql-data
    networks:
      - identity-service
volumes:
  sql-data: