apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
spec:
  type: ClusterIP
  selector:
    app: restaurant-redis-deployment
  ports:
  - name: sql-port
    port: 9666
    targetPort: 6379
