apiVersion: v1
kind: Service
metadata:
  name: restaurant-booking-ci-api
spec:
  type: ClusterIP
  selector:
    app: restaurant-booking-api
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
